### ISSUE TITLE
webclient page is broken with OF 4.9.0

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-llama-plugin#7]
Issue with plugin on Openfire 4.9.0

After upgrade to OF 4.9.0 the webclient page is broken. Same code works fine with OF 4.7.5.
I did rebuild plugin with latest code + mvn but same issue persist

Many thanks in advance if this can be fixed

++

![screenshot2](https://github.com/user-attachments/assets/5b5c13b9-9ea8-46aa-af6a-3b8ed3440bb0)
![screenshot3](https://github.com/user-attachments/assets/a9947bbd-1bb3-4a9d-93a3-7b9e3af414ab)

**Comment by ClaudeStabile** [comment]
Error i have found in logs is 

```
2024.10.08 11:36:15.532 ^[[1;31mERROR^[[m [PluginMonitorExec-5]: org.jivesoftware.openfire.session.LocalSession - Erreur interne du serveur**
java.lang.IllegalArgumentException: IQ must be of type 'set' or 'get'. Original IQ: <iq type="error" id="728-11" from="www.free-solutions.org" to="llama@www.free-solutions.org/llama-1728380175526"><error code="403" type="auth"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">You cannot set a VCard for an address that is not you. Please update the 'to' address of your request to match your bare JID.</text></error></iq>
        at org.xmpp.packet.IQ.createResultIQ(IQ.java:378) ~[tinder-2.0.0.jar:?]
        at org.ifsoft.llama.openfire.LLaMAConnection.deliver(LLaMAConnection.java:286) ~[llama-0.0.2-SNAPSHOT.jar:?]
        at org.jivesoftware.openfire.session.LocalClientSession.deliver(LocalClientSession.java:954) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.session.LocalSession.process(LocalSession.java:408) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.spi.RoutingTableImpl.routeToLocalDomain(RoutingTableImpl.java:405) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.spi.RoutingTableImpl.routePacket(RoutingTableImpl.java:327) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.net.SocketPacketWriteHandler.process(SocketPacketWriteHandler.java:65) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.spi.PacketDelivererImpl.deliver(PacketDelivererImpl.java:53) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.handler.IQHandler.process(IQHandler.java:128) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.IQRouter.handle(IQRouter.java:403) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.IQRouter.route(IQRouter.java:106) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.ifsoft.llama.openfire.LLaMAConnection.<init>(LLaMAConnection.java:102) ~[llama-0.0.2-SNAPSHOT.jar:?]
        at org.ifsoft.llama.openfire.LLaMA.loginLLaMAUser(LLaMA.java:323) ~[llama-0.0.2-SNAPSHOT.jar:?]
        at org.ifsoft.llama.openfire.LLaMA.initializePlugin(LLaMA.java:121) ~[llama-0.0.2-SNAPSHOT.jar:?]
        at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:640) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:380) ~[xmppserver-4.9.0.jar:4.9.0]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:368) ~[xmppserver-4.9.0.jar:4.9.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
2024.10.08 11:36:16.089 ^[[32mINFO ^[[m [PluginMonitorExec-5]: org.ifsoft.llama.openfire.LLaMAConnection - xmpp session created for llama
2024.10.08 11:36:16.090 ^[[32mINFO ^[[m [PluginMonitorExec-5]: org.ifsoft.llama.openfire.LLaMA - llama initiated
2024.10.08 11:36:16.102 ^[[32mINFO ^[[m [PluginMonitorExec-5]: org.jivesoftware.openfire.container.PluginManager - Successfully loaded plugin 'llama-0.0.2-SNAPSHOT'.
2024.10.08 11:36:16.120 ^[[32mINFO ^[[m [pool-8-thread-1]: org.ifsoft.llama.openfire.LLaMAConnection - getJson from LLaMA null https://chatgpt.free-solutions.ch/completion
{"n_predict":2048,"top_p":0.9,"stream":true,"slot_id":3,"top_k":40,"temperature":0.9,"system_prompt":{"assistant_name":"LLaMA","anti_prompt":"User:","prompt":"Il s'agit d'une conversation entre Utilisateur et Llama, un chatbot sympathique. Llama est serviable, gentil, honnête, doué pour l'écriture et ne manque jamais de répondre immédiatement et avec précision à toutes les questions."},"prompt":"[INST]what is your name?[/INST]","cache_prompt":false}
```

**Comment by guusdk** [comment]
I don't expect the stacktrace to be relevant to the problem that you're seeing.

**Comment by ClaudeStabile** [comment]
OkiDoki, I will check with Dele, i suppose i am the first one using this with OF 4.9.0, will see. 
FYI 4.7.5 is working with same plugin code.
